version: '3'
services:
    frontend:
        build: .
        stdin_open: true
        tty: true
        ports:
          - "8080:8080"
        volumes:
          - "/app/node_modules"
          - ".:/app"